language: php

php:
  - 7.1
  - 7.2

install: travis_retry composer install --no-interaction --optimize-autoloader

script:
  - vendor/bin/phpstan analyse --no-progress --level 7 src tests
  - vendor/bin/tester -s -p php tests
